### ISSUE TITLE
Player

### ISSUE THREAD

**Issue by foshechka** [Porco-Rosso/vkdl#14]
You'd better do a good player instead of unnecessary imaging. :-1:

**Comment by Porco-Rosso** [comment]
Instead of complaining, I'd prefer for you to submit some pull requests.

If you don't like the update, you are free to use the [2.0.0 release](https://github.com/Porco-Rosso/vkdl/releases/tag/v2.0.0), or fork it and work on it yourself.

Ultimately I am going to code what I feel like making. Although I appreciate input, it better be constructive. Here you are just being rude.
