### ISSUE TITLE
search speed

### ISSUE THREAD

**Issue by foshechka** [Porco-Rosso/vkdl#9]
Why search speed is less than the standard script? What affects the speed of the impact of the results?

**Comment by Porco-Rosso** [comment]
The search speed is entirely dependent on the speed of the replies from vk.com

I guess is that more recent queries get cached by vk.com on their servers. I think this because searching the same query returns results much faster the second time. Also that would explain why searching for more popular songs produce results faster.

Because the bottleneck is not on the coding side (apart from playlist loading), there is nothing I can do about it.

**Comment by foshechka** [comment]
I say this because I think that in the script alashova Search works quickly and vkdl something to think about.

**Comment by Porco-Rosso** [comment]
I have no idea why his script would be faster. It's exactly the same in terms of search. I think his code even requests more results then mine does. maybe it has something to do with it being served through rawgit? 

In case you are interested below is the stats:
![screen shot 2015-06-17 at 10 19 47 pm](https://cloud.githubusercontent.com/assets/7024527/8216395/01f4d24c-153f-11e5-8a1f-3b059eb7ef77.png)

**Comment by foshechka** [comment]
Ok, thnks.
